services:
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: web-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - setutu-network

networks:
  setutu-network:
    driver: bridge
